# This file is managed by Centy. Use the Centy CLI to modify it.
name: Comment
icon: chat-bubble
identifier: uuid
features:
  displayNumber: false
  priority: false
  softDelete: false
  assets: false
  orgSync: false
  move: false
  duplicate: false
customFields:
- name: item_id
  type: string
  required: false
- name: item_type
  type: string
  required: false
- name: author
  type: string
  required: false
